Health System logic
DeimosA/PlayingWithMagic pull request #34
Opened 2020-04-05 09:34 UTC by JacopoG

Hi,

I'm working on issue #6, this pull request is just to get some feedback on the logic.

I tried to implemented the logic in the simplest way, so I used the Signal/Listener API offered by Ashley. The Health System receive an ExplosionHitsPlayerEvent and it update the health. The event contains the player entity. Basically I delegated all the collision logic outside.

Other things to consider:
- [ ] health points default value
- [ ] bomb damage value and where to put it

2020-04-14 08:47 UTC, DeimosA requested changes

2020-04-14 08:47 UTC, DeimosA commented on core/src/no/group15/playmagic/ecs/components/HealthComponent.kt
> +class HealthComponent : Component {
Should be poolable

2020-04-14 08:47 UTC, DeimosA commented on core/src/no/group15/playmagic/ecs/components/HealthComponent.kt
> +	var points : Int = 100 // TODO chose a good default value?
Max health can be stored as its own val

2020-04-14 09:30 UTC, JacopoG commented
@DeimosA I added the Poolable interface to the component (I have to do it also in other branches). I also added a maxPoints variable, check if that's what you meant!

2020-04-18 08:58 UTC, DeimosA approved these changes

2020-04-18 08:58 UTC, merged